/**
 * src/types/notification.js
 *
 * Purpose:
 * Canonical Notification domain model for RailSentinel. This file is the
 * authoritative definition of what a Notification record is: its fields,
 * allowed enum values, field-level documentation, default values, Hindi
 * (PA broadcast) content support metadata, and relationship references
 * to other domain models.
 *
 * A Notification is an outbound alert or message generated by the
 * RailSentinel platform to inform operators, station staff, or passengers
 * about incidents, risk breaches, crowd alerts, schedule conflicts, or
 * energy anomalies. Notifications are dispatched across one or more
 * channels: in-app, push, SMS, email, voice, and/or PA (Public Address /
 * station announcement system), which requires Hindi content for IR.
 *
 * NotificationsPage channel mapping:
 *   critical → ['PA', 'SMS', 'Email']    (life-safety / halt)
 *   high     → ['SMS', 'Email']
 *   medium+  → ['Email']
 *   in-app   → always available regardless of priority
 *
 * NotificationCard field alignment (M5 component):
 *   notification.priority      → 'low' | 'medium' | 'high' | 'critical'
 *   notification.status        → 'unread' | 'read' | 'acknowledged' | 'dismissed'
 *   notification.deliveryStatus→ 'pending' | 'sent' | 'delivered' | 'failed' | 'retrying'
 *   notification.channel       → 'push' | 'sms' | 'email' | 'in-app' | 'voice' | 'pa'
 *   notification.audience[]    → recipient role / group descriptors
 *   notification.body          → full notification body text (displayed in card)
 *   notification.sentAt        → ISO timestamp (drives relativeTime in card)
 *   notification.locale        → 'en' | 'hi' | …
 *
 * Architecture rules:
 *   - No API logic — does not fetch, send, or transform HTTP payloads.
 *   - No UI logic — does not import React, design tokens, or components.
 *   - No store logic — does not import or call Zustand.
 *   - Used by: notificationService.js (mapping), useNotifications.js,
 *     M5 components (prop validation), and future TypeScript migration.
 *
 * Schema fields:
 *   id                    — Unique notification identifier (UUID / string)
 *   title                 — Notification headline (shown in card header)
 *   body                  — Full notification body text (shown in card body)
 *   message               — Alias for body (legacy / API compatibility)
 *   summary               — One-line summary for list / search
 *   priority              — Notification urgency: NOTIF_PRIORITY enum
 *   priorityLabel         — Named label from priority: P1–P4 (derived)
 *   channel               — Primary dispatch channel: NOTIF_CHANNEL enum
 *   channels              — All channels this notification was dispatched on
 *   status                — Reader / operator lifecycle: NOTIF_STATUS enum
 *   deliveryStatus        — Transport delivery state: DELIVERY_STATUS enum
 *   recipientType         — Audience category: RECIPIENT_TYPE enum
 *   audience              — Array of recipient role / group descriptor strings
 *   recipientIds          — Specific recipient IDs (user IDs or device IDs)
 *   recipientCount        — Total number of recipients targeted
 *   locale                — Primary locale: 'en' | 'hi' | 'en-hi' | …
 *   template              — Template name / ID used to generate content
 *   templateVersion       — Version of the content template
 *   category              — Notification domain category: NOTIF_CATEGORY enum
 *   sourceType            — The domain type that generated this notification
 *   sourceId              — ID of the entity that triggered the notification
 *   sourceName            — Human-readable name of the trigger entity
 *   isRead                — Whether the primary recipient has read the notification
 *   isAcknowledged        — Whether an operator has acknowledged
 *   isDismissed           — Whether an operator has dismissed
 *
 * PA Broadcast / Hindi content support:
 *   isPaBroadcast         — True when channel includes 'pa' (Public Address)
 *   paBroadcastText       — English PA script (plain text for TTS / announcer)
 *   paBroadcastTextHi     — Hindi PA script (हिन्दी) for bilingual announcements
 *   paStationCode         — Station code where PA should be broadcast
 *   paPlatformNumber      — Target platform number (null = all platforms)
 *   paRepeatCount         — Number of times to repeat the announcement
 *   paScheduledAt         — ISO timestamp when PA should be broadcast (null = immediate)
 *   paBroadcastAt         — ISO timestamp when PA was actually broadcast
 *   paZone                — Broadcast zone within station (null = station-wide)
 *
 *   retryCount            — Number of delivery retries attempted
 *   maxRetries            — Maximum retries configured
 *   failureReason         — Reason for delivery failure (null if not failed)
 *   expiresAt             — ISO timestamp after which notification is no longer valid
 *   createdAt             — ISO timestamp of record creation
 *   sentAt                — ISO timestamp when notification was dispatched
 *   deliveredAt           — ISO timestamp of confirmed delivery
 *   readAt                — ISO timestamp when marked read
 *   acknowledgedAt        — ISO timestamp of operator acknowledgement
 *   dismissedAt           — ISO timestamp of dismissal
 *   updatedAt             — ISO timestamp of last modification
 *   lastUpdatedAt         — Store-canonical alias for updatedAt
 *   syncedAt              — ISO timestamp of last backend sync
 *   linkedIncidentIds     — IDs of Incident records this notification relates to
 *   linkedTrainIds        — IDs of Train records this notification relates to
 *   linkedCrowdIds        — IDs of CrowdForecast records this notification relates to
 *   linkedRiskScoreIds    — IDs of RiskScore records this notification relates to
 *   tags                  — Arbitrary string tags
 *   version               — Optimistic-concurrency version counter
 *   meta                  — Arbitrary extension object for future fields
 *
 * Relationships:
 *   Notification → Incident[]      via linkedIncidentIds     (M-to-M)
 *   Notification → Train[]         via linkedTrainIds        (M-to-M)
 *   Notification → CrowdForecast[] via linkedCrowdIds        (M-to-M)
 *   Notification → RiskScore[]     via linkedRiskScoreIds    (M-to-M)
 *   Notification → entity          via sourceType + sourceId (polymorphic)
 *   Notification → Station         via paStationCode         (optional)
 *
 * Dependencies:
 *   - None. Pure JS constants and plain objects.
 *
 * Exports:
 *   - NOTIF_PRIORITY       → frozen enum: priority band values (aligned with colors.NOTIFICATION)
 *   - NOTIF_CHANNEL        → frozen enum: delivery channel values (incl. PA)
 *   - NOTIF_STATUS         → frozen enum: reader/operator lifecycle values
 *   - DELIVERY_STATUS      → frozen enum: transport delivery state values
 *   - RECIPIENT_TYPE       → frozen enum: audience category values
 *   - NOTIF_CATEGORY       → frozen enum: notification domain category values
 *   - NOTIF_LOCALE         → frozen enum: supported locale codes with Hindi flag
 *   - NOTIF_SORT           → frozen enum: valid sort key strings
 *   - NOTIF_FIELD          → frozen map: field name → metadata
 *   - NOTIF_DEFAULTS       → frozen default Notification record
 *   - createNotification   → factory: merges partial with defaults
 *   - isValidNotification  → validator: minimum-contract check
 *   - normalizeNotification → normalizer: coerces raw payload to valid shape
 *   - Notification (default) → frozen reference object
 */

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

function deepFreeze(obj) {
  Object.getOwnPropertyNames(obj).forEach((name) => {
    const value = obj[name];
    if (value && typeof value === 'object') {
      deepFreeze(value);
    }
  });
  return Object.freeze(obj);
}

// ---------------------------------------------------------------------------
// NOTIF_PRIORITY
// Urgency band aligned with:
//   - colors.NOTIFICATION in src/design/colors.js (P1–P4)
//   - NotificationsPage priorityLabel() helper
//   - NotificationCard PRIORITY_CONFIG (low/medium/high/critical)
//   - CONFLICT_PRIORITY in schedule.js (same P1–P4 labels)
// ---------------------------------------------------------------------------

export const NOTIF_PRIORITY = deepFreeze({
  /** Immediate — life-safety / station halt / platform evacuation (P1) */
  CRITICAL: 'critical',
  /** Urgent — major disruption, operator action required within 15 min (P2) */
  HIGH:     'high',
  /** Standard — respond within 1 hour (P3) */
  MEDIUM:   'medium',
  /** Informational / monitoring only (P4) */
  LOW:      'low',

  /** P-label lookup (matches NotificationsPage priorityLabel()) */
  pLabel: {
    critical: 'P1',
    high:     'P2',
    medium:   'P3',
    low:      'P4',
  },

  /** UI display config matching NotificationCard PRIORITY_CONFIG */
  uiConfig: {
    critical: { rank: 3, label: 'Critical', cssModifier: 'critical', icon: '✕' },
    high:     { rank: 2, label: 'High',     cssModifier: 'high',     icon: '▲' },
    medium:   { rank: 1, label: 'Medium',   cssModifier: 'medium',   icon: '◉' },
    low:      { rank: 0, label: 'Low',      cssModifier: 'low',      icon: '○' },
  },

  /**
   * Default channels per priority (matches NotificationsPage channelForSeverity()).
   * Always append 'in-app' to every result at the application layer.
   */
  defaultChannels: {
    critical: ['pa', 'sms', 'email'],
    high:     ['sms', 'email'],
    medium:   ['email'],
    low:      [],
  },

  /** Ordered descending urgency */
  orderedDesc: ['critical', 'high', 'medium', 'low'],
});

// ---------------------------------------------------------------------------
// NOTIF_CHANNEL
// Delivery channel. PA (Public Address) is Indian-railway specific and
// requires Hindi bilingual content (paBroadcastText / paBroadcastTextHi).
// Aligned with NotificationCard CHANNEL_ICON map and NotificationsPage
// channelForSeverity() helper.
// ---------------------------------------------------------------------------

export const NOTIF_CHANNEL = deepFreeze({
  /** In-app notification (bell / sidebar) — always available */
  IN_APP:  'in-app',
  /** Push notification (mobile / PWA) */
  PUSH:    'push',
  /** SMS text message */
  SMS:     'sms',
  /** Email */
  EMAIL:   'email',
  /** Voice call / IVR */
  VOICE:   'voice',
  /** Station Public Address system — bilingual EN/HI announcement */
  PA:      'pa',
  /** Webhook / system-to-system callback */
  WEBHOOK: 'webhook',
  /** Printed / physical notice (for scheduling, not real-time) */
  PRINT:   'print',

  /** Channel icon map (matches NotificationCard CHANNEL_ICON) */
  icons: {
    'in-app': '🔔',
    push:     '📲',
    sms:      '💬',
    email:    '✉',
    voice:    '🔊',
    pa:       '📢',
    webhook:  '🔗',
    print:    '🖨',
  },

  /** Channels that require Hindi bilingual content */
  requiresHindi: ['pa'],
  /** Channels with real-time delivery (SLA < 60s) */
  realtime: ['in-app', 'push', 'pa', 'sms'],

  /** Ordered display list */
  ordered: ['in-app', 'push', 'sms', 'email', 'voice', 'pa', 'webhook', 'print'],
});

// ---------------------------------------------------------------------------
// NOTIF_STATUS
// Reader / operator lifecycle. Aligned with NotificationCard STATUS_CONFIG
// and NotificationsPage status checks (acknowledged / dismissed).
// ---------------------------------------------------------------------------

export const NOTIF_STATUS = deepFreeze({
  /** Delivered to recipient but not yet viewed */
  UNREAD:        'unread',
  /** Recipient has viewed the notification */
  READ:          'read',
  /** Operator has formally acknowledged and taken ownership */
  ACKNOWLEDGED:  'acknowledged',
  /** Operator has dismissed (does not require action) */
  DISMISSED:     'dismissed',
  /** Notification has expired / been superseded */
  EXPIRED:       'expired',

  /** UI display config matching NotificationCard STATUS_CONFIG */
  uiConfig: {
    unread:       { label: 'Unread',       cssModifier: 'unread'       },
    read:         { label: 'Read',         cssModifier: 'read'         },
    acknowledged: { label: 'Acknowledged', cssModifier: 'acknowledged' },
    dismissed:    { label: 'Dismissed',    cssModifier: 'dismissed'    },
    expired:      { label: 'Expired',      cssModifier: 'expired'      },
  },

  /** Terminal states — no further action expected */
  terminal: ['dismissed', 'expired'],
  /** Active (open) filter states */
  active: ['unread', 'read', 'acknowledged'],
});

// ---------------------------------------------------------------------------
// DELIVERY_STATUS
// Transport-layer delivery state. Aligned with NotificationCard
// DELIVERY_CONFIG (pending / sent / delivered / failed / retrying).
// ---------------------------------------------------------------------------

export const DELIVERY_STATUS = deepFreeze({
  /** Queued — not yet dispatched */
  PENDING:   'pending',
  /** Dispatched to transport provider */
  SENT:      'sent',
  /** Delivery confirmed by transport provider */
  DELIVERED: 'delivered',
  /** Delivery failed — no further retries */
  FAILED:    'failed',
  /** Retry in progress after a failure */
  RETRYING:  'retrying',
  /** Delivery skipped (e.g. recipient opted out) */
  SKIPPED:   'skipped',

  /** UI display config matching NotificationCard DELIVERY_CONFIG */
  uiConfig: {
    pending:   { label: 'Pending',   cssModifier: 'pending'   },
    sent:      { label: 'Sent',      cssModifier: 'sent'      },
    delivered: { label: 'Delivered', cssModifier: 'delivered' },
    failed:    { label: 'Failed',    cssModifier: 'failed'    },
    retrying:  { label: 'Retrying',  cssModifier: 'retrying'  },
    skipped:   { label: 'Skipped',   cssModifier: 'skipped'   },
  },

  /** States where notification needs operator attention */
  needsAttention: ['failed', 'retrying'],
  /** Terminal states */
  terminal: ['delivered', 'failed', 'skipped'],
});

// ---------------------------------------------------------------------------
// RECIPIENT_TYPE
// High-level audience category. Controls routing and template selection.
// ---------------------------------------------------------------------------

export const RECIPIENT_TYPE = deepFreeze({
  /** Single identified operator / controller */
  OPERATOR:        'operator',
  /** Broadcast to all operators in a zone / shift */
  OPERATOR_GROUP:  'operator_group',
  /** Station controller role */
  STATION_STAFF:   'station_staff',
  /** Train crew / loco pilot */
  TRAIN_CREW:      'train_crew',
  /** Passengers at a specific station platform (PA only) */
  PASSENGER:       'passenger',
  /** Maintenance / engineering team */
  MAINTENANCE:     'maintenance',
  /** Management / supervisor escalation */
  MANAGEMENT:      'management',
  /** External agency (police, fire, NDRF) */
  EXTERNAL:        'external',
  /** System-to-system webhook target */
  SYSTEM:          'system',
  /** Unknown / unspecified */
  UNKNOWN:         'unknown',

  /** Types that can receive PA broadcasts */
  paEligible: ['passenger', 'station_staff'],
  /** Ordered display list */
  ordered: [
    'operator', 'operator_group', 'station_staff', 'train_crew',
    'passenger', 'maintenance', 'management', 'external', 'system',
  ],
});

// ---------------------------------------------------------------------------
// NOTIF_CATEGORY
// Domain category identifying what generated the notification.
// ---------------------------------------------------------------------------

export const NOTIF_CATEGORY = deepFreeze({
  INCIDENT:  'incident',
  RISK:      'risk',
  CROWD:     'crowd',
  TRAIN:     'train',
  SCHEDULE:  'schedule',
  ENERGY:    'energy',
  SYSTEM:    'system',
  SECURITY:  'security',
  WEATHER:   'weather',
  OTHER:     'other',

  ordered: [
    'incident', 'risk', 'crowd', 'train',
    'schedule', 'energy', 'security', 'weather', 'system', 'other',
  ],
});

// ---------------------------------------------------------------------------
// NOTIF_LOCALE
// Supported locale codes. Hindi (hi) is required for PA broadcasts.
// IR standard is bilingual EN + HI for all PA announcements.
// ---------------------------------------------------------------------------

export const NOTIF_LOCALE = deepFreeze({
  /** English (default) */
  EN:    'en',
  /** Hindi (Devanagari script — required for PA broadcasts) */
  HI:    'hi',
  /** Bilingual English + Hindi (used when both scripts are needed) */
  EN_HI: 'en-hi',
  /** Bengali — used in ER/SER zones */
  BN:    'bn',
  /** Tamil — used in SR zone */
  TA:    'ta',
  /** Telugu — used in SCR zone */
  TE:    'te',
  /** Kannada — used in SWR zone */
  KN:    'kn',
  /** Marathi — used in CR/WR zones */
  MR:    'mr',
  /** Gujarati — used in WR zone */
  GU:    'gu',
  /** Punjabi — used in NR zone */
  PA_LANG: 'pa',

  /** Locales required for PA (Public Address) broadcasts on Indian Railways */
  paRequired: ['en', 'hi'],
  /** All supported locale codes */
  all: ['en', 'hi', 'en-hi', 'bn', 'ta', 'te', 'kn', 'mr', 'gu', 'pa'],
});

// ---------------------------------------------------------------------------
// NOTIF_SORT
// ---------------------------------------------------------------------------

export const NOTIF_SORT = deepFreeze({
  CREATED_DESC:   'createdAt_desc',
  CREATED_ASC:    'createdAt_asc',
  PRIORITY_DESC:  'priority_desc',
  PRIORITY_ASC:   'priority_asc',
  SENT_DESC:      'sentAt_desc',
  SENT_ASC:       'sentAt_asc',
  UPDATED_DESC:   'lastUpdatedAt_desc',
  UPDATED_ASC:    'lastUpdatedAt_asc',

  DEFAULT: 'createdAt_desc',
});

// ---------------------------------------------------------------------------
// NOTIF_FIELD
// Field-level metadata map.
// ---------------------------------------------------------------------------

export const NOTIF_FIELD = deepFreeze({
  id: {
    key: 'id', label: 'Notification ID',
    type: 'string', required: true, indexed: true,
  },
  title: {
    key: 'title', label: 'Title',
    type: 'string', required: true, indexed: false,
    note: 'Displayed as card header in NotificationCard.',
  },
  body: {
    key: 'body', label: 'Body',
    type: 'string', required: false, indexed: false,
    note: 'Full text displayed in NotificationCard body.',
  },
  message: {
    key: 'message', label: 'Message (alias)',
    type: 'string', required: false, indexed: false,
    note: 'Legacy alias for body — kept in sync.',
  },
  summary: {
    key: 'summary', label: 'Summary',
    type: 'string', required: false, indexed: false,
  },
  priority: {
    key: 'priority', label: 'Priority',
    type: 'NOTIF_PRIORITY', required: true, indexed: true,
    note: 'Aligned with colors.NOTIFICATION and NotificationCard PRIORITY_CONFIG.',
  },
  priorityLabel: {
    key: 'priorityLabel', label: 'Priority Label',
    type: 'string (P1–P4)', required: false, indexed: false,
    note: 'Derived from priority via NOTIF_PRIORITY.pLabel.',
  },
  channel: {
    key: 'channel', label: 'Channel',
    type: 'NOTIF_CHANNEL', required: true, indexed: true,
    note: 'Primary channel displayed in NotificationCard.',
  },
  channels: {
    key: 'channels', label: 'All Channels',
    type: 'NOTIF_CHANNEL[]', required: false, indexed: false,
  },
  status: {
    key: 'status', label: 'Status',
    type: 'NOTIF_STATUS', required: true, indexed: true,
    note: 'Drives NotificationCard STATUS_CONFIG CSS modifiers.',
  },
  deliveryStatus: {
    key: 'deliveryStatus', label: 'Delivery Status',
    type: 'DELIVERY_STATUS', required: false, indexed: true,
    note: 'Drives NotificationCard DELIVERY_CONFIG CSS modifiers.',
  },
  recipientType: {
    key: 'recipientType', label: 'Recipient Type',
    type: 'RECIPIENT_TYPE', required: false, indexed: true,
  },
  audience: {
    key: 'audience', label: 'Audience',
    type: 'string[]', required: false, indexed: false,
    note: 'Role/group descriptor array. Displayed in NotificationCard audienceLabel.',
  },
  recipientIds: {
    key: 'recipientIds', label: 'Recipient IDs',
    type: 'string[]', required: false, indexed: false,
  },
  recipientCount: {
    key: 'recipientCount', label: 'Recipient Count',
    type: 'number', required: false, indexed: false,
  },
  locale: {
    key: 'locale', label: 'Locale',
    type: 'NOTIF_LOCALE', required: false, indexed: true,
    note: 'Drives template language selection. PA broadcasts must include "hi".',
  },
  template: {
    key: 'template', label: 'Template',
    type: 'string', required: false, indexed: false,
    note: 'Template name/ID — read by NotificationCard.',
  },
  templateVersion: {
    key: 'templateVersion', label: 'Template Version',
    type: 'string', required: false, indexed: false,
  },
  category: {
    key: 'category', label: 'Category',
    type: 'NOTIF_CATEGORY', required: false, indexed: true,
  },
  sourceType: {
    key: 'sourceType', label: 'Source Type',
    type: 'string', required: false, indexed: true,
  },
  sourceId: {
    key: 'sourceId', label: 'Source ID',
    type: 'string', required: false, indexed: true,
  },
  sourceName: {
    key: 'sourceName', label: 'Source Name',
    type: 'string', required: false, indexed: false,
  },
  isRead:         { key: 'isRead',         type: 'boolean',  required: false, indexed: true,  label: 'Is Read'         },
  isAcknowledged: { key: 'isAcknowledged', type: 'boolean',  required: false, indexed: true,  label: 'Is Acknowledged' },
  isDismissed:    { key: 'isDismissed',    type: 'boolean',  required: false, indexed: true,  label: 'Is Dismissed'    },
  // ── PA / Hindi fields ──────────────────────────────────────────────────
  isPaBroadcast: {
    key: 'isPaBroadcast', label: 'PA Broadcast',
    type: 'boolean', required: false, indexed: true,
    note: 'True when channels includes "pa". Activates Hindi content requirement.',
  },
  paBroadcastText: {
    key: 'paBroadcastText', label: 'PA Script (English)',
    type: 'string', required: false, indexed: false,
    note: 'English announcement text for TTS or station announcer.',
  },
  paBroadcastTextHi: {
    key: 'paBroadcastTextHi', label: 'PA Script (Hindi)',
    type: 'string', required: false, indexed: false,
    note: 'Hindi (हिन्दी) announcement text. Mandatory when isPaBroadcast=true.',
  },
  paStationCode: {
    key: 'paStationCode', label: 'PA Station Code',
    type: 'string', required: false, indexed: true,
  },
  paPlatformNumber: {
    key: 'paPlatformNumber', label: 'PA Platform',
    type: 'string', required: false, indexed: false,
  },
  paRepeatCount: {
    key: 'paRepeatCount', label: 'PA Repeat Count',
    type: 'number', required: false, indexed: false,
  },
  paScheduledAt: {
    key: 'paScheduledAt', label: 'PA Scheduled At',
    type: 'ISO8601', required: false, indexed: false,
  },
  paBroadcastAt: {
    key: 'paBroadcastAt', label: 'PA Broadcast At',
    type: 'ISO8601', required: false, indexed: false,
  },
  paZone: {
    key: 'paZone', label: 'PA Zone',
    type: 'string', required: false, indexed: false,
    note: 'Broadcast zone within station (e.g. "concourse", "platform-4"). Null = station-wide.',
  },
  // ── Delivery reliability ────────────────────────────────────────────────
  retryCount:    { key: 'retryCount',    type: 'number',  required: false, indexed: false, label: 'Retry Count'    },
  maxRetries:    { key: 'maxRetries',    type: 'number',  required: false, indexed: false, label: 'Max Retries'    },
  failureReason: { key: 'failureReason', type: 'string',  required: false, indexed: false, label: 'Failure Reason' },
  expiresAt:     { key: 'expiresAt',     type: 'ISO8601', required: false, indexed: false, label: 'Expires At'     },
  // ── Timestamps ─────────────────────────────────────────────────────────
  createdAt:     { key: 'createdAt',     type: 'ISO8601', required: false, indexed: true,  label: 'Created At'     },
  sentAt:        { key: 'sentAt',        type: 'ISO8601', required: false, indexed: true,  label: 'Sent At', note: 'Drives relativeTime in NotificationCard.' },
  deliveredAt:   { key: 'deliveredAt',   type: 'ISO8601', required: false, indexed: false, label: 'Delivered At', note: 'Displayed in NotificationDetailPanel.' },
  readAt:        { key: 'readAt',        type: 'ISO8601', required: false, indexed: false, label: 'Read At'        },
  acknowledgedAt:{ key: 'acknowledgedAt',type: 'ISO8601', required: false, indexed: false, label: 'Acknowledged At'},
  dismissedAt:   { key: 'dismissedAt',   type: 'ISO8601', required: false, indexed: false, label: 'Dismissed At'   },
  updatedAt:     { key: 'updatedAt',     type: 'ISO8601', required: false, indexed: false, label: 'Updated At'     },
  lastUpdatedAt: { key: 'lastUpdatedAt', type: 'ISO8601', required: false, indexed: false, label: 'Last Updated', note: 'Store-canonical alias for updatedAt.' },
  syncedAt:      { key: 'syncedAt',      type: 'ISO8601', required: false, indexed: false, label: 'Synced At'      },
  // ── Relationships ──────────────────────────────────────────────────────
  linkedIncidentIds:  { key: 'linkedIncidentIds',  type: 'string[]', required: false, indexed: false, label: 'Linked Incidents'       },
  linkedTrainIds:     { key: 'linkedTrainIds',     type: 'string[]', required: false, indexed: false, label: 'Linked Trains'          },
  linkedCrowdIds:     { key: 'linkedCrowdIds',     type: 'string[]', required: false, indexed: false, label: 'Linked Crowd Forecasts' },
  linkedRiskScoreIds: { key: 'linkedRiskScoreIds', type: 'string[]', required: false, indexed: false, label: 'Linked Risk Scores'     },
  tags:               { key: 'tags',               type: 'string[]', required: false, indexed: false, label: 'Tags'                   },
  version:            { key: 'version',            type: 'number',   required: false, indexed: false, label: 'Version'                },
  meta:               { key: 'meta',               type: 'object',   required: false, indexed: false, label: 'Meta'                   },
});

// ---------------------------------------------------------------------------
// NOTIF_DEFAULTS
// ---------------------------------------------------------------------------

export const NOTIF_DEFAULTS = deepFreeze({
  id:                    '',
  title:                 '',
  body:                  '',
  message:               '',        // alias — kept in sync with body
  summary:               '',
  priority:              NOTIF_PRIORITY.LOW,
  priorityLabel:         'P4',
  channel:               NOTIF_CHANNEL.IN_APP,
  channels:              [],
  status:                NOTIF_STATUS.UNREAD,
  deliveryStatus:        DELIVERY_STATUS.PENDING,
  recipientType:         RECIPIENT_TYPE.OPERATOR,
  audience:              [],
  recipientIds:          [],
  recipientCount:        0,
  locale:                NOTIF_LOCALE.EN,
  template:              '',
  templateVersion:       '',
  category:              NOTIF_CATEGORY.SYSTEM,
  sourceType:            '',
  sourceId:              null,
  sourceName:            '',
  isRead:                false,
  isAcknowledged:        false,
  isDismissed:           false,
  // PA / Hindi
  isPaBroadcast:         false,
  paBroadcastText:       '',
  paBroadcastTextHi:     '',
  paStationCode:         null,
  paPlatformNumber:      null,
  paRepeatCount:         3,
  paScheduledAt:         null,
  paBroadcastAt:         null,
  paZone:                null,
  // Delivery reliability
  retryCount:            0,
  maxRetries:            3,
  failureReason:         null,
  expiresAt:             null,
  // Timestamps
  createdAt:             null,
  sentAt:                null,
  deliveredAt:           null,
  readAt:                null,
  acknowledgedAt:        null,
  dismissedAt:           null,
  updatedAt:             null,
  lastUpdatedAt:         null,
  syncedAt:              null,
  // Relationships
  linkedIncidentIds:     [],
  linkedTrainIds:        [],
  linkedCrowdIds:        [],
  linkedRiskScoreIds:    [],
  tags:                  [],
  version:               1,
  meta:                  {},
});

// ---------------------------------------------------------------------------
// createNotification
// Factory — merges a partial record with NOTIF_DEFAULTS.
// Auto-derives:
//   priorityLabel from priority
//   isPaBroadcast from channels[]
//   channels[] when only channel (single) is given
//   body ↔ message alias sync
//   isRead / isAcknowledged / isDismissed from status
//
// @param {Partial<typeof NOTIF_DEFAULTS>} partial
// @returns {typeof NOTIF_DEFAULTS}
// ---------------------------------------------------------------------------

export function createNotification(partial = {}) {
  if (!partial || typeof partial !== 'object') {
    return { ...NOTIF_DEFAULTS };
  }

  const now = new Date().toISOString();

  // Resolve priority
  const priority = partial.priority ?? NOTIF_DEFAULTS.priority;
  const priorityLabel = partial.priorityLabel ?? NOTIF_PRIORITY.pLabel[priority] ?? 'P4';

  // Resolve body ↔ message alias
  const body    = partial.body    ?? partial.message ?? NOTIF_DEFAULTS.body;
  const message = partial.message ?? body;

  // Resolve channels[]
  const channel = partial.channel ?? NOTIF_DEFAULTS.channel;
  const channels = Array.isArray(partial.channels) && partial.channels.length > 0
    ? partial.channels
    : channel ? [channel] : [];

  // Derive isPaBroadcast
  const isPaBroadcast = typeof partial.isPaBroadcast === 'boolean'
    ? partial.isPaBroadcast
    : channels.includes(NOTIF_CHANNEL.PA);

  // Derive read/ack/dismissed booleans from status if not explicitly set
  const status = partial.status ?? NOTIF_DEFAULTS.status;
  const isRead = typeof partial.isRead === 'boolean'
    ? partial.isRead
    : ['read', 'acknowledged', 'dismissed'].includes(status);
  const isAcknowledged = typeof partial.isAcknowledged === 'boolean'
    ? partial.isAcknowledged
    : status === 'acknowledged';
  const isDismissed = typeof partial.isDismissed === 'boolean'
    ? partial.isDismissed
    : status === 'dismissed';

  return {
    ...NOTIF_DEFAULTS,
    ...partial,
    priority,
    priorityLabel,
    body,
    message,
    channel,
    channels,
    status,
    isPaBroadcast,
    isRead,
    isAcknowledged,
    isDismissed,
    // Ensure array fields
    audience:              Array.isArray(partial.audience)              ? partial.audience              : NOTIF_DEFAULTS.audience,
    recipientIds:          Array.isArray(partial.recipientIds)          ? partial.recipientIds          : NOTIF_DEFAULTS.recipientIds,
    linkedIncidentIds:     Array.isArray(partial.linkedIncidentIds)     ? partial.linkedIncidentIds     : NOTIF_DEFAULTS.linkedIncidentIds,
    linkedTrainIds:        Array.isArray(partial.linkedTrainIds)        ? partial.linkedTrainIds        : NOTIF_DEFAULTS.linkedTrainIds,
    linkedCrowdIds:        Array.isArray(partial.linkedCrowdIds)        ? partial.linkedCrowdIds        : NOTIF_DEFAULTS.linkedCrowdIds,
    linkedRiskScoreIds:    Array.isArray(partial.linkedRiskScoreIds)    ? partial.linkedRiskScoreIds    : NOTIF_DEFAULTS.linkedRiskScoreIds,
    tags:                  Array.isArray(partial.tags)                  ? partial.tags                  : NOTIF_DEFAULTS.tags,
    meta: (partial.meta && typeof partial.meta === 'object' && !Array.isArray(partial.meta))
      ? { ...partial.meta }
      : {},
    // Timestamps
    createdAt:     partial.createdAt     ?? now,
    updatedAt:     partial.updatedAt     ?? now,
    lastUpdatedAt: partial.lastUpdatedAt ?? partial.updatedAt ?? now,
    version: (typeof partial.version === 'number' && partial.version > 0) ? partial.version : 1,
  };
}

// ---------------------------------------------------------------------------
// isValidNotification
//
// @param {unknown} obj
// @returns {boolean}
// ---------------------------------------------------------------------------

export function isValidNotification(obj) {
  if (!obj || typeof obj !== 'object') return false;
  if (!obj.id || typeof obj.id !== 'string' || obj.id.trim() === '') return false;
  if (!obj.title) return false;
  if (!obj.priority) return false;
  if (!obj.status) return false;
  return true;
}

// ---------------------------------------------------------------------------
// normalizeNotification
// Coerces a raw API payload to a valid Notification shape.
// Handles aliases:
//   notificationId     → id
//   notification_id    → id
//   text / content     → body / message
//   delivery_status    → deliveryStatus
//   recipient_type     → recipientType
//   pa_text            → paBroadcastText
//   pa_text_hi         → paBroadcastTextHi
//   pa_station         → paStationCode
//   sent_at            → sentAt
//   delivered_at       → deliveredAt
//   created_at         → createdAt
//   updated_at         → updatedAt
//
// @param {unknown} raw
// @returns {typeof NOTIF_DEFAULTS | null}
// ---------------------------------------------------------------------------

export function normalizeNotification(raw) {
  if (!raw || typeof raw !== 'object') return null;

  const id = raw.id ?? raw.notificationId ?? raw.notification_id ?? null;
  if (!id) return null;

  // Body / message alias
  const body    = raw.body    ?? raw.message ?? raw.text    ?? raw.content ?? '';
  const message = raw.message ?? body;

  // Delivery status
  const deliveryStatus = raw.deliveryStatus ?? raw.delivery_status ?? NOTIF_DEFAULTS.deliveryStatus;

  // Recipient type
  const recipientType = raw.recipientType ?? raw.recipient_type ?? NOTIF_DEFAULTS.recipientType;

  // PA fields
  const paBroadcastText   = raw.paBroadcastText   ?? raw.pa_text    ?? '';
  const paBroadcastTextHi = raw.paBroadcastTextHi ?? raw.pa_text_hi ?? '';
  const paStationCode     = raw.paStationCode     ?? raw.pa_station  ?? null;

  // Timestamps
  const sentAt        = raw.sentAt        ?? raw.sent_at        ?? null;
  const deliveredAt   = raw.deliveredAt   ?? raw.delivered_at   ?? null;
  const createdAt     = raw.createdAt     ?? raw.created_at     ?? null;
  const updatedAt     = raw.updatedAt     ?? raw.updated_at     ?? createdAt ?? null;
  const lastUpdatedAt = raw.lastUpdatedAt ?? updatedAt ?? null;
  const readAt        = raw.readAt        ?? raw.read_at        ?? null;
  const acknowledgedAt= raw.acknowledgedAt ?? raw.acknowledged_at ?? null;
  const dismissedAt   = raw.dismissedAt   ?? raw.dismissed_at   ?? null;

  return createNotification({
    ...raw,
    id,
    body,
    message,
    deliveryStatus,
    recipientType,
    paBroadcastText,
    paBroadcastTextHi,
    paStationCode,
    sentAt,
    deliveredAt,
    createdAt,
    updatedAt,
    lastUpdatedAt,
    readAt,
    acknowledgedAt,
    dismissedAt,
  });
}

// ---------------------------------------------------------------------------
// Notification — reference schema object (default export)
// ---------------------------------------------------------------------------

/**
 * Canonical Notification domain model — reference shape.
 * PA broadcast example: critical crowd alert at New Delhi, bilingual EN/HI.
 *
 * @example
 * import Notification from '../types/notification.js';
 */
const Notification = deepFreeze({
  // ── Identity ──────────────────────────────────────────────────────────────
  id:                    'NTF-88001',
  title:                 'CRITICAL: Platform 4 crowd capacity breach imminent — New Delhi',
  body:                  'Platform 4 at New Delhi (NDLS) is forecast to exceed safe capacity within 15 minutes. Immediate crowd management deployment required. Trains 12301 and 22691 arriving on Platform 4.',
  message:               'Platform 4 at New Delhi (NDLS) is forecast to exceed safe capacity within 15 minutes. Immediate crowd management deployment required. Trains 12301 and 22691 arriving on Platform 4.',
  summary:               'Crowd breach imminent — NDLS Platform 4',

  // ── Priority & routing ────────────────────────────────────────────────────
  priority:              NOTIF_PRIORITY.CRITICAL,
  priorityLabel:         'P1',
  channel:               NOTIF_CHANNEL.PA,
  channels:              [NOTIF_CHANNEL.PA, NOTIF_CHANNEL.SMS, NOTIF_CHANNEL.IN_APP],

  // ── Lifecycle ─────────────────────────────────────────────────────────────
  status:                NOTIF_STATUS.UNREAD,
  deliveryStatus:        DELIVERY_STATUS.DELIVERED,

  // ── Recipients ────────────────────────────────────────────────────────────
  recipientType:         RECIPIENT_TYPE.STATION_STAFF,
  audience:              ['Station Controller', 'RPF', 'Platform Staff — P4'],
  recipientIds:          ['USR-0089', 'USR-0091', 'USR-0095'],
  recipientCount:        18,

  // ── Content ───────────────────────────────────────────────────────────────
  locale:                NOTIF_LOCALE.EN_HI,
  template:              'crowd-breach-critical-v2',
  templateVersion:       '2.1.0',
  category:              NOTIF_CATEGORY.CROWD,
  sourceType:            'crowd_forecast',
  sourceId:              'CF-00321',
  sourceName:            'New Delhi Platform 4 Crowd Forecast',

  // ── Reader state ──────────────────────────────────────────────────────────
  isRead:                false,
  isAcknowledged:        false,
  isDismissed:           false,

  // ── PA Broadcast / Hindi ──────────────────────────────────────────────────
  isPaBroadcast:         true,
  paBroadcastText:       'Attention passengers on Platform Number 4. Due to heavy crowding, please use alternative platforms and exits. Railway staff will assist you. Thank you.',
  paBroadcastTextHi:     'प्लेटफ़ॉर्म नंबर 4 पर यात्रियों का ध्यान आकर्षित किया जाता है। अत्यधिक भीड़ के कारण, कृपया अन्य प्लेटफ़ॉर्म और निकास का उपयोग करें। रेलवे कर्मचारी आपकी सहायता करेंगे। धन्यवाद।',
  paStationCode:         'NDLS',
  paPlatformNumber:      '4',
  paRepeatCount:         3,
  paScheduledAt:         null,
  paBroadcastAt:         '2025-06-10T09:59:00.000Z',
  paZone:                null,

  // ── Delivery reliability ──────────────────────────────────────────────────
  retryCount:            0,
  maxRetries:            3,
  failureReason:         null,
  expiresAt:             '2025-06-10T10:30:00.000Z',

  // ── Timestamps ────────────────────────────────────────────────────────────
  createdAt:             '2025-06-10T09:58:30.000Z',
  sentAt:                '2025-06-10T09:58:45.000Z',
  deliveredAt:           '2025-06-10T09:58:50.000Z',
  readAt:                null,
  acknowledgedAt:        null,
  dismissedAt:           null,
  updatedAt:             '2025-06-10T09:58:50.000Z',
  lastUpdatedAt:         '2025-06-10T09:58:50.000Z',
  syncedAt:              '2025-06-10T09:58:55.000Z',

  // ── Relationships ─────────────────────────────────────────────────────────
  linkedIncidentIds:     [],
  linkedTrainIds:        ['TRN-12301', 'TRN-22691'],
  linkedCrowdIds:        ['CF-00321'],
  linkedRiskScoreIds:    ['RSK-00112'],
  tags:                  ['critical', 'crowd', 'ndls', 'pa', 'p4'],

  // ── Concurrency ───────────────────────────────────────────────────────────
  version:               1,

  // ── Extension ─────────────────────────────────────────────────────────────
  meta:                  {},
});

export default Notification;
